-- [문제](https://school.programmers.co.kr/learn/courses/30/lessons/299310)

SELECT
YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
(J.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, -- (1) JOIN 절에서 호출된 J 사용
ID
FROM
ECOLI_DATA AS E
JOIN
(SELECT
YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM
ECOLI_DATA -- (2) 여기서 ECOLI_DATA 대신 E를 쓰면 에러
GROUP BY
YEAR(DIFFERENTIATION_DATE)
) AS J
ON
J.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY
YEAR ASC, YEAR_DEV ASC